rsyslog/rsyslog-doc

- source/configuration/modules/imtcp.rst
Added new options to rsyslog in this [pull request](https://github.com/rsyslog/rsyslog/pull/175).  Adding respective documentation.  Is actually mostly just copy pasted from imptcp documentation for same options.
> Adding config module documentation for imtcp keep alive options.

- source/rainerscript/functions.rst
From testing a regular expression it seemed re_match uses ERE (as does re_extract). Please verify if this is indeed true and then add it to the documentation so others can easily find it.
> Indicate re_match uses ERE as well. Please verify.

- source/concepts/ns_gtls.rst
- source/configuration/modules/mmsnmptrapd.rst
- source/configuration/modules/omlibdbi.rst
- source/configuration/modules/ommongodb.rst
- source/configuration/modules/ommysql.rst
- source/configuration/modules/omrelp.rst
- source/tutorials/tls.rst
- source/tutorials/tls_cert_summary.rst
Apart from a trivial merge conflict, this can also be merged to stable-v8.
> "server" typos in stable-v7 branch

- source/tutorials/reliable_forwarding.rst
In the docs for [Reliable Forwarding of syslog Messages with Rsyslog](http://www.rsyslog.com/doc/v8-stable/tutorials/reliable_forwarding.html) the code snippets are not formatted properly. I've fix the source file for the docs with what I assume is the correct line breaks. 
I've also used syntax highlighting that is part of a default sphinx installation.
I hope this all makes sense. Let me know if you want me to change anything.
> Fix code block in tutorial doc

- source/configuration/actions.rst
- source/configuration/basic_structure.rst
- source/rainerscript/control_structures.rst
- Added doc-fragment for action.copyMsg
- Dedup: Got basic-structure page to point to control-structures page from RainerScript section, which talks about control-flow structures in more detail.
- Dedup: Got basic-structure page to point to set/unset/reset documentation in RainerScript section, which talks about mutating statements in much more detail.
> Documented new action param (action.copyMsg) + some minor restructuring

- source/concepts/queues.rst
- source/configuration/modules/imjournal.rst
- source/configuration/properties.rst
- source/rainerscript/queue_parameters.rst
- source/whitepapers/queues_analogy.rst
I corrected some typos here.
I also found that some default values are missing and some parameters are not explained for queues. I think that 9750 is wrong for queue.discardmark. I also couldn't see the dynamic values working for the watermarks, as Changelog suggests for 8.1.2, unless that was reverted.
> Correct typos

- source/configuration/modules/omelasticsearch.rst
This note would hopefully clarify how to handle https://github.com/rsyslog/rsyslog/issues/89. I've also tested the solution of installing the self signed certificate on the rsyslog machine and it can send logs to Elasticsearch having an Apache in front of it configured similarly to here: https://github.com/rsyslog/rsyslog/pull/44#issuecomment-46010743
> Added note about self-signed certs for omelasticsearch

- source/configuration/modules/workflow.rst
I fixed two typos and removed "newly" because we are now at version 8.
> Minor Typo Fixes

- source/configuration/global/index.rst
default MaxMessageSize is 8096 bytes, as per `iMaxLine` in https://github.com/rsyslog/rsyslog/blob/master/runtime/glbl.c#L86
I was having a hard time hitting the limit in my tests :-)
> Update default value for $MaxMessageSize

- source/configuration/index.rst
Remove the sentence "All configuration directives need to be specified on a line by their own and must start with a dollar-sign." as that is no longer true.
> Remove reference to legacy configuration format

- source/tutorials/tls_cert_machine.rst
When running this today you get the following notice:
```shell
example@hostname:/etc/rsyslog.d# certtool --generate-privkey --outfile key.pem --bits 4096
** Note: Please use the --sec-param instead of --bits
Generating a 4096 bit RSA private key...
```
For this reason, I am suggesting the move to `--sec-param` to match the suggestion of the tool.
> Update certtool request per latest version suggestions

- source/concepts/multi_ruleset.rst
Misspelt 'specific' and also fixed the ruleset name match the name in the input directive.
> Typo fixes in English and syntax

- source/configuration/modules/imptcp.rst
- source/configuration/modules/imuxsock.rst
Wording was still based on legacy config format and thus
quite confusing as used.
> re-word description

- source/configuration/global/index.rst
Present in all branches at least since v7-stable.
> Small typo in a legacy directive

- source/configuration/dyn_stats.rst
was introduced for test stabilization, but is useful stat anyway
> added purge_triggered counter to dyn-stats doc

- source/configuration/modules/omhiredis.rst
Support for option password parameter for authenticated redis database. If not provided AUTH command wont be sent to the server.
> Password option for authenticated redis database.

- source/configuration/action/index.rst
- source/configuration/global/index.rst
ActionQueueTimeoutEnqueue 0 means "discard immediately" and not "indefinite".
For the reference: http://www.rsyslog.com/doc/v8-stable/concepts/queues.html#filled-up-queues
> Fix mistake: indefinite -> discard immediately

- source/configuration/modules/imuxsock.rst
Default value for RateLimit.Interval was changed from 5 to 0 in the following commit: https://github.com/rsyslog/rsyslog/commit/76c4d6b951453078ab53bf612caf0b8ec9d54bb8
> Fix SysSock.RateLimit.Interval default: 5 -> 0

- source/configuration/action/index.rst
- source/configuration/global/index.rst
`$<object>QueueTimeoutEnqueue 0` means "discard immediately" and not "indefinite".
For the reference: http://www.rsyslog.com/doc/v7-stable/concepts/queues.html#filled-up-queues
>  Fix mistake: indefinite -> discard immediately (v7-stable)

- source/configuration/modules/imfile.rst
> Fix: /path/to/state/file -> name-of-state-file

- source/configuration/modules/mmjsonparse.rst
see also https://github.com/rsyslog/rsyslog/issues/940
> bugfix: "cookie" parameter was missing in mmjsonparse

- source/rainerscript/queue_parameters.rst
According to the sources, rsyslog emits an error whenever : pThis->iFullDlyMrk < pThis->iHighWtrMrk
> Correct wording of fulldelaymark parameter

- source/rainerscript/global.rst
Hello
In the source file runtime/glbl.c, iMaxLine is set to 8192.
Regards/
> Correct default value for $MaxMessageSize

- source/configuration/parser.rst
As there is no example within rsyslog documentation that gives an example how to use multiple Parsers in a ruleset I added this example.
> Added example for using multiple parsers within rulesets

- source/configuration/modules/ompgsql.rst
This adds documentation for the PostgreSQL output module. It also mentions template support, which depends on the PR for adding/fixing this support for the Postgres output: https://github.com/rsyslog/rsyslog/pull/1087
> Add documentation for ompgsql

- source/tutorials/tls_cert_scenario.rst
Basically, _e_ was missing from _have_.
> Fix a typo in tls_cert_scenario.rst.

- source/configuration/filters.rst
The expressions.rst source file moved to ../rainerscript/expressions.rst.
The fix cannot be tested on GitHub since our source files are .rst, not .html.
> Change the hyperlink to the expressions.html

- source/configuration/properties.rst
Added notice about rawmsg being processed to escape control characters, fixing https://github.com/rsyslog/rsyslog/issues/1159
> Add notice about rawmsg escaping control characters

- source/configuration/modules/imfile.rst
As discussed in http://lists.adiscon.net/pipermail/rsyslog/2016-October/043279.html, and after code review https://github.com/rsyslog/rsyslog/blob/master/runtime/stream.c#L815
> Update imfile.rst to state readmode=2 support SP and TAB

- source/rainerscript/queue_parameters.rst
Document queue.samplinginterval parameter added on https://github.com/rsyslog/rsyslog/pull/1142
> Document queue.samplinginterval parameter

- source/rainerscript/queue_parameters.rst
Add description for queue parameter `queue.samplinginterval`.
See [PR#1142](https://github.com/rsyslog/rsyslog/pull/1142).
> Add description for queue.samplinginterval

- source/configuration/modules/omprog.rst
There are additional parameters like 'output' and 'forcesingleinstance' which are not documented. 
Thought about documenting them too, but then realized it may be deliberate. 
Are they not documented because they are incomplete and/or not ready for endusers? They do seem to have some corner-cases, hence the question.
> omprog documentation update to surface signalOnClose control

- source/configuration/modules/imptcp.rst
processOnPoller was documented as an Input Parameter. In fact, it is a module parameter. Moved to correct location in documentation.
> Correct processOnPoller documentation.

- source/configuration/modules/imudp.rst
- source/configuration/modules/omfwd.rst
19e5d06f6637 added support for bind-to-device option for omfwd and
imudp modules. Add description for the option.
Signed-off-by: David Ahern <dsa@cumulusnetworks.com>
> Add description for bind-to-device option

- source/configuration/modules/omfile.rst
Correct default value for veryRobustZip parameter according to the [sources](https://github.com/rsyslog/rsyslog/blob/master/tools/omfile.c#L1085)
> Fix default value for veryRobustZip

- source/configuration/templates.rst
Hello
as far as I understand, RFC5424 is the actual syslog standard and is implemented by template _SyslogProtocol23Format_.
Let me know if you agree with thiis template description.
> Update description of template SyslogProtocol23Format

- source/rainerscript/queue_parameters.rst
According to the [sources](https://github.com/rsyslog/rsyslog/blob/master/runtime/queue.c#L1425), default batch size is now 128.
> Correct dequeuebatchsize

- source/configuration/modules/omfile.rst
Hello
according to my understanding of this recent [change](https://github.com/rsyslog/rsyslog/pull/1364), FlushOnTXEnd set to off causes Rsyslog to wait till the buffer becomes to write it to disk full regardless of asyncWriting.
> Correct FlushOnTXEnd note

- source/configuration/modules/imfile.rst
Thanks to Jon Henry for pointing out this info was missing.
see also https://github.com/rsyslog/rsyslog/issues/1531
> imfile: mention "polling" mode is default if $ModLoad is used

- source/configuration/filters.rst
See line 212 in the same file where it is correct.
Arguably we start counting at 1 (i know, programmers sometimes start counting at 0).
We may want to change the wording to remove this ambiguous column number completely ("first column"?)
> First character is in column 1 not 0

- source/configuration/modules/imjournal.rst
- deprecation of "usepidfromsystem"
> imjournal: new option "usepid"

- source/configuration/parser.rst
Replaced "load(module" with "module(load".
> Correct syntax for loading parser modules

- source/configuration/modules/omfwd.rst
see also https://github.com/rsyslog/rsyslog/pull/1666
note: https://github.com/rsyslog/rsyslog/pull/1666 needs to be merged before applying this!
> omfwd: document that "maxerrormessages" parameter is deprecated

- source/configuration/modules/omkafka.rst
This was [added as `partitions.usefixed`](https://github.com/rsyslog/rsyslog/commit/98a04073233d94b2e09a07536fec8f0cbe1c66b9) and never changed. The code also seems grammatically right, so adapt the documentation.
I assume the difference in capitalisation is deliberate since it's the same on all the multi-word options?
> Fix typo in the omkafka options

- source/rainerscript/functions.rst
Adds documentation for the format_time() function.
Also fixes some spelling mistakes.
> Add RainerScript format_time() function.

- .gitignore
- source/rainerscript/functions.rst
Adds documentation for the `parse_time()` function.
See rsyslog/rsyslog#1925 and rsyslog/rsyslog#971.
> Add RainerScript parse_time() function.

- source/configuration/action/index.rst
changed queue parameters defaults to match those in https://github.com/rsyslog/rsyslog-doc/blob/50dea260fb7b1818661e81dc7577ef0b5fbd74fd/source/rainerscript/queue_parameters.rst#general-queue-parameters
> updated legacy config queue defaults

- source/configuration/modules/mmjsonparse.rst
Hello
I've discovered that mmjsonparse is able to create a JSON document if given a non-CEE/lumberjack message, however this feature isn't yet documented.
Regards
dud
> Document mmjsonparse JSON creation feature

- source/configuration/modules/ommongodb.rst
Add documentation on new directives: uristr, ssl_cert, ssl_ca
action(type="ommongodb"
uristr="mongodb://vulture:9091,vulture2:9091/?replicaset=Vulture&ssl=true"
ssl_cert="/var/db/mongodb/mongod.pem"
ssl_ca="/var/db/mongodb/ca.pem"
db="logs" collection="syslog")
> New ommongodb module using mongo-c-driver

- source/whitepapers/queues_analogy.rst
> Corrected two broken links on the "Turning Lanes and Rsyslog Queues" page

- source/configuration/modules/imuxsock.rst
> imuxsock doc: Removed legacy format warning from new style content

- source/rainerscript/global.rst
I unintentionally messed up the spacing when I added this parameter in rsyslog/rsyslog-doc#369. This commit fixes that issue.
> Fix spacing issue with parser.permitSlashInProgramName parameter

- source/conf.py
- source/configuration/conf_formats.rst
@rgerhards Since we're already using these references in other documents (e.g., #427), I'm going ahead and submitting this batch of changes now instead of waiting until the other docs have been updated.
refs rsyslog/rsyslog-doc#421
> Shorten format substitution reference names

- README.md
- Fix small typo
- Update direction to note that we are installing in our new virtual environment and not to the local path used by the "--user" flag
refs rsyslog/rsyslog-doc#405, rsyslog/rsyslog-doc#406
> Fix typo and invalid environment reference introduced in PR #406

- .gitignore
Helps prevent editors (at least the ones I use) with integrated Git support from flagging temp files as changes that I should be aware of.
> Add sphinx-build temp dir to .gitignore

- source/conf.py
Use a list comprehension in order to work equally well on Python 2 or Python 3. 
I originally tested in the recommended Python 2 build environment and had no issues. I _believe_ I also tested in a Python 3.5.x environment without problems, but tonight when attempting to build on a Windows 10 box with Python 3.6.3 I got some Python 3 specific errors:
```
TypeError: '<' not supported between instances of 'map' and 'map'
```
I found the workaround here:
https://stackoverflow.com/questions/2574080/sorting-a-list-of-dot-separated-numbers-like-software-versions
> Fix git tag sort compatibility with Python 3.6.x

- source/configuration/modules/imrelp.rst
- source/rainerscript/global.rst
@rgerhards Please let me know what you think.
refs rsyslog/rsyslog-doc#432
> Attempt to better emphasize relationship between global maxMessageSize, imrelp's MaxDataSize parameters

- source/configuration/modules/imrelp.rst
Looks like someone may have left the word behind from a previous edit.
refs rsyslog/rsyslog-doc#109
> imrelp: Remove stray word

- source/configuration/modules/imfile.rst
- Fix typos
- Emphasize that unless the PersistStateInterval parameter is set,
no state files will be created
- Note that state files are only read on startup
- Mention "advanced format" global workDirectory parameter alongside
the $WorkDirectory directive for comparison
refs rsyslog/rsyslog#2159
> imfile: Add clarification re state files, fix typos

- source/configuration/filters.rst
Instead of using hard-coded page references (which is likely something from the past html-based docs setup), use sphinx doc references instead.
closes rsyslog/rsyslog-doc#166
> Fix page references

- README.md
closes rsyslog/rsyslog-doc#443
> README: Explicitly note that the instructions are for building the docs.

- source/rainerscript/functions.rst
Adds documentation for the `is_time()` function.
See rsyslog/rsyslog#2246 and rsyslog/rsyslog#1624.
> Add RainerScript is_time() function

- source/configuration/examples.rst
- source/configuration/global/options/rsconf1_debugprintcfsyslinehandlerlist.rst
- source/configuration/global/options/rsconf1_debugprintmodulelist.rst
- source/configuration/global/options/rsconf1_debugprinttemplatelist.rst
- Remove empty sections and trailing transition markers (reSTructuredText does not permit ending with a transition)
- Replace broken source link with full target link
refs rsyslog/rsyslog-doc#463, rsyslog/rsyslog-doc#455
> Minor fixup for c0fb71c

- source/conf.py
- source/configuration/modules/imuxsock.rst
Follow-up questions (for my next commit to the branch behind this PR):
- **TODO**: How does rsyslog obtain the log socket from systemd?
- **TODO**: Is ``sysSock.Use`` ignored for systemd systems? It seems to be (I saw the statement that the `SysSock.` parameters are often ignored).
refs rsyslog/rsyslog-doc#397
**EDIT**
The branch sourced by this PR is viewable here: 
http://rsyslog.whyaskwhy.org/i-397/configuration/modules/imuxsock.html
> imuxsock: Additional details, section, alt wording

- build.sh
@rgerhards I found some issues with the build script when attempting to use it as-is for automating regular builds of the branches. I'm not sure that I have all of them squashed, but this fixes at least the most glaring ones. I suspect I'll loop back to this script and make some further tweaks as part of another PR after I have a chance to spend some more time with it.
closes rsyslog/rsyslog-doc#464
> build.sh: Fix typos, block accidental commits

- release_build.sh
the build.sh does too many things that are not directly related
to release build process
closes https://github.com/rsyslog/rsyslog-doc/issues/469
> re-add release_build.sh script: used by maintainer during release

- source/configuration/global/index.rst
Thanks to 朱继鹏 (github user jipengzhu) for alerting us on this
bug.
closes https://github.com/rsyslog/rsyslog/issues/1742
> obsolete format: fix default number of main message queue wrkr threads

- source/conf.py
Add option to disable warning for unknown project files to Sphinx build configuration file. This mutes the spurious warnings shown when building epub files.
closes rsyslog/rsyslog-doc#477
> Mute "unknown mimetype" warnings for epub format

- release_build.sh
Add support for pulling in version number from command-line. This can be used in overriding the hash-based version number now used by default for devel builds.
Additionally, the release build script no longer attempts to include build scripts in the doc release tarball.
closes rsyslog/rsyslog-doc#482
> Update build script to accept version/release info from command-line

- README.md
Add links to issues with 'good first issue' and 'help wanted' labels to help new contributors get started.
> Add links to starter issues

- source/configuration/modules/imuxsock.rst
> Instead of trying to give too many details in the parameter entry, forward the reader to the dedicated section for the topic of systemd and imuxsock interaction.
@rgerhards I kept getting hung up on the existing wording while working on variations of the prototype formats in PR #476. I'm hoping this simpler approach will read better and let the dedicated module doc section handle stepping the reader through the interaction with systemd (vs trying to replicate it in multiple places).
> Attempt to clarify SysSock.Use parameter use

- source/containers/container_features.rst
- source/containers/docker_specifics.rst
- source/containers/index.rst
- source/index.rst
The idea is to provide useful information as early as possible and
extend it as it grows. While this at first may look sparse, I think
it is the best way forward. The alternative would be to wait a
long time until we know "everything" and can document it.
see also https://github.com/rsyslog/rsyslog-doc/issues/491
> begin documentation on rsyslog containers

- source/configuration/modules/mmrm1stspace.rst
This fixes the display of the config sample as the text is now rendered as a code block instead of raw text:
http://www.rsyslog.com/doc/v8-stable/configuration/modules/mmrm1stspace.html
closes rsyslog/rsyslog-doc#307
> Add missing newline after literal code marker

- README.md
This PR is meant to be merged in tandem with PR #497 to take advantage of the changes introduced there.
- Cover an "assumed" step (that new Linux users will know how to install Git) and provide a forwarding link for more info
- Update pip install command to use the new `requirements.txt` file instead of hard-coding the specific single package in the README (which may change as additional dependencies are introduced such as custom themes, plugins, etc).
refs rsyslog/rsyslog-doc#497
> README: Add Git install and pip requirements

- source/configuration/modules/impstats.rst
- Swap out existing section header characters for those used in Python Style Guide and the Sphinx documentation
- Add example output from module
- Add explanation of 'size' counter, emphasize that it tracks log messages flowing through the associated object
- minor formatting tweaks (still much to do)
- Purged obsolete legacy configuration examples, sections
since there are advanced format examples already included
refs rsyslog/rsyslog-doc#438
refs http://www.rsyslog.com/periodic-statistics-on-rsyslog-counters/
closes rsyslog/rsyslog-doc#500
> impstats: Headers, trim legacy, example output

- source/containers/container_features.rst
- source/containers/index.rst
- Typo fix
- Use 'kbd' Sphinx directive to highlight the specific keystroke used to exit rsyslog
- Add comments noting points for future expansion
> Minor tweaks to Container-Features doc

- source/index.rst
The footnote references were broken and the 'Related Links' section was bare, so I pruned them and moved the Sponsors link just below the 'Sponsors and Community' section intentionally so it stands out.
Once some PRs ahead of this one goes through I plan to move the external link reference to
the substitution definitions file (again, in another PR) since this is probably not the only place we will reference the Sponsors link.
Additionally, I removed the explicit link text for the "How You Can Help" page since the title for that page is used if you do not override it with explicit link text.
The changes should be live here soon:
http://rsyslog.whyaskwhy.org/i502-footnote-fixes/
closes rsyslog/rsyslog-doc#502
> Remove broken footnotes, 'Related Links' section

- source/rainerscript/configuration_objects.rst
- source/rainerscript/include.rst
- source/rainerscript/index.rst
The documents the new objects and its properties.
Note that I did deliberately not try to get to a "nice formatting", as
we are currently standardizing on something, and so a change is needed
in any case. Even more so, the whole (Rainer)Script documentation needs
to be restructured. So this patch gives the necessary information on
include(), but does not try to improve the state of the doc by itself.
see also https://github.com/rsyslog/rsyslog/pull/2426
> document the new 8.33 include() object

- source/_static/rsyslog.css
- source/conf.py
- source/configuration/modules/imuxsock.rst
This is early work to prototype a consistent format for module parameters. 
Some of the formats I've observed:
- Bullet points
- use of  `.. function::` directives with "default" statement just beneath
- ... with "default" statement at the end
- bullet point, noting whether parameter is mandatory and then default value (one-liner)
I don't know what the right answer is, so this PR is more of a fence post for conversation than anything else. Because I recently worked on the imuxsock module doc, I'll test some changes to that doc first.
- Refs: #6
---
Live view of work:
- [section headers with `obsolete legacy` format directives](http://rsyslog.whyaskwhy.org/imuxsock_parameter_syntax/configuration/modules/imuxsock.html)
> PROTOTYPE: Parameter formatting

- BUILDS_README.md
- README.md
- cron_build_all_branches.sh
- release_build.sh
- source/conf.py
- source/conf_helpers.py
- source/index.rst
This is intended for use with dev builds of the docs to quickly identify what branch the docs were bult from. This also helps with epub builds as some readers do not always display the "release" details prominently once the file has been opened.
Note: Looks like my editor applied some whitespace trimming when I saved the index file, so the commit isn't entirely "clean".
@rgerhards What do you think? The results should be visible here soon (builds are performed every 15 minutes, takes just under 10 minutes to complete):
http://rsyslog.whyaskwhy.org/display_branch_build_info/
> Update build process to default to static value builds, use verbose details for dev builds when available

- source/configuration/conf_formats.rst
Correct "prior to" statement to reflect the current major version.
refs rsyslog/rsyslog-doc#413
> Correct versions affected by performance impact when using the "advanced" format

- source/configuration/filters.rst
Since initial improvements in v7 and later parity of performance in v8, there is no longer any difference in speed between the basic "selector lines" and advanced formats when filtering messages.
closes rsyslog/rsyslog-doc#413
> Emphasize no perf diff between formats

- source/conf.py
- source/substitution_definitions.inc.rst
Instead of maintaining the substitution definitions within the Sphinx build configuration file, those definitions have been moved to a separate include file. 
Accordingly, the build conf has been updated to add an exclude entry for all `*.inc.rst` files so that they are not included multiple times during build processing. This include file is currently referenced by the `rst_prolog` build conf option.
> Move substitution definitions to include file

- source/conf.py
- source/footer.inc.rst
> Instead of maintaining the substitution definitions within the Sphinx build configuration file, those definitions have been moved to a separate include file. Accordingly, the build conf has been updated to add an exclude entry for all *.inc.rst files so that they are not included multiple times during build
> processing. This include file is currently referenced by the rst_prolog build conf option.
> 
> A footer has been created and is included by all pages via an include statement within the rst_epilog build conf option. This footer is an attempt to display common "go here for help" options that should be made prominent for newcomers to the project.
@rgerhards What do you think about this idea? For the final merge, I would probably break up the two changes into either separate PRs or …
> Add standard footer

- source/rainerscript/functions.rst
Add coverage of `random()` function. Not yet complete, waiting on feedback for related ticket.
closes rsyslog/rsyslog-doc#460
> Add random function coverage

- .gitignore
- .travis.yml
- tools/README.md
- tools/buildenv/.dockerignore
- tools/buildenv/Dockerfile
- tools/buildenv/README.md
- tools/buildenv/starter.sh
- tools/buildenv/tools/bash
- tools/buildenv/tools/build-doc
- tools/buildenv/tools/git-clone
- tools/buildenv/tools/help
- tools/buildenv/tools/version-info
This is to be extended, but provides a first impression of how
this could be done. It's useful in any case to use during CI, as
it permits to reproduce exact same results in different environments.
To give the container a try, you need a system with docker installed. Then, run
```
$ docker run -v /path/to/rsyslog-doc_home_dir:/rsyslog-doc rsyslog/rsyslog_doc_gen
```
I have uploaded the container image to above docker hub location.
> tooling: initial standard build container definition

- cron_build_all_branches.sh
Instead of using the GNU sort utility's "version sort" option, fall back to a combination of options that appear to provide the same effect, but also work well with busybox (used in some docker container images).
refs rsyslog/rsyslog-doc#524
> cron script: mimic '--version-sort' option for busybox compatibility

- tools/buildenv/Dockerfile
I see where you're checking first to make sure that they don't already have a bind mount for a checked out version of the docs. If the docs are found, they're built as-is without changing the checked out branch. If they don't already have a copy of the docs, then a git clone operation occurs, a checkout call and then a build of the checked out branch. That makes sense. You're essentially emulating someone calling `sphinx-build -b html source build` directly against content in the current working directory.
Provided that the docker image is not meant to be dedicated to building the stable version of the docs, I suggest favoring `master` over `v8-stable` as that fallback branch choice is likely to be of greater interest  to someone opting to build the docs on their own.
> Dockerfile: Change default branch to build from v8-stable to master

- source/rainerscript/functions.rst
See rsyslog/rsyslog-doc#510 for earlier discussion.
@davidelang Ignoring the whitespace trim that snuck in, do you see anything else that needs modification here? I pulled the `versionchanged` directive since it didn't seem to make sense to highlight that something _had_ changed with the function if the intended effect did not.
Ignoring the whitespace changes, this is what I modified:
```diff
.. warning::
-   The random number must not be assumed to be crypto-grade. rsyslog will
-   attempt to use a crypto-grade source if available, but it will fall
-   back to a very weak random number generator if a crypto-grade source
-   is not available.
+   The random number must not be assumed to be crypto-grade.
.. versionadded:: 8.12.0
-.. versionchanged:: 8.31.0
-   If a crypto-grade random …
```
> Remove references to "crypto" from random() func

- source/conf.py
- source/conf_helpers.py
Prior hard-coded dev build string:
`rsyslog 8.xx-BRANCH-YYYYMMDD-commit_hash documentation`
That format has been given a name of 'detailed'. 
A new simpler format has been defined as:
`rsyslog commit_hash docs`
Stable release build strings still use the format of:
`rsyslog 8.x.x documentation`
As before, epub release builds default to the release build strings. epub dev builds still use the detailed release string format. This is because the display of epub files is not affected in the same way as HTML output using themes that are more narrowly restricted in horizontal space.
*Assuming you already have Python and Sphinx installed ...*
1. git clone https://github.com/deoren/rsyslog-doc rsyslog-doc-testing
1. cd rsyslog-doc-testing
1. git checkout i537-short-dev-build-release-string
1. …
> Build: Set 'simple' dev build string as default

- source/rainerscript/constant_strings.rst
Small clarification as suggested by @davidelang.
- refs rsyslog/rsyslog-doc#512
- closes rsyslog/rsyslog-doc#544
> Clarify that string constants are set at startup

- tools/buildenv/Dockerfile
- tools/buildenv/README.md
- tools/buildenv/starter.sh
- tools/buildenv/tools/build-doc
- tools/buildenv/tools/help
PR now contains a bit more, see individual commits. Still think all of these features make sense together, and sparing time to do separate PRs (that would need to build on each other).
> container: fix quoted parameter passing to container build

- source/configuration/modules/omrelp.rst
Copied from omfwd module doc and slightly modified to remove mention of TCP/UDP specifics.
My assumption (which is why I'm not going ahead and merging this), is that the behavior between the RebindInterval parameter for omrelp and omfwd is the same, but I don't know that for sure.
I plan to rework the formatting for this doc once PR #476 is reviewed/merged, but for now I just used the existing format in order to go ahead and solve the reported issue.
closes rsyslog/rsyslog-doc#345
> omrelp: Add RebindInterval parameter

- tools/buildenv/Dockerfile
The docker container is for the rsyslog-doc project, and should be
agnostic to its users. So it was a bad idea in the first place to
put a website-only dependency into the container. Now removing that.
see also https://github.com/rsyslog/rsyslog-doc/pull/543#issuecomment-364761077
> fix docker container: contained rsyslog.com site theme

- source/configuration/modules/imuxsock.rst
- Add 'max' column for integer-based parameters
- Only used for "burst" parameters right now, but by adding for all integer-based parameters we make it more obvious that we haven't recorded the maximum values for the others yet
- Fill in max burst value as provided by Rainer
closes rsyslog/rsyslog-doc#541
> imuxsock: Add "max" column, fill in burst limit

- source/includes/container_dev_env.inc.rst
- source/includes/substitution_definitions.inc.rst
- source/installation/install_from_source.rst
- source/installation/packages.rst
- source/installation/rsyslog_docker.rst
What started as a focused effort turned into me wandering around some related docs and tweaking various items, creating new substitution references, fixing some old HTML doc page references and performing some general cleanup.
- Loosely related to rsyslog/rsyslog-doc#525
- refs rsyslog/rsyslog-doc#452 (a few hard-coded references were fixed here)
@rgerhards Any concerns with this PR?
> Update subst refs, language tweaks, misc fixes

- source/configuration/modules/imuxsock.rst
The heading for the module parameter was named global parameter.
> imuxsock: change false heading

- source/configuration/templates.rst
I only intended to fix the typos, but since my editor automatically trimmed the trailing space I kept those changes too.
refs rsyslog/rsyslog-doc#560
> templates: Fix typos, trim trailing space

- source/configuration/modules/omstdout.rst
Module documentation was rewritten in the style.
Additionally parameter with the new config style were added.
closes https://github.com/rsyslog/rsyslog-doc/issues/547
> omstdout: rewrite documentation

- source/configuration/modules/impstats.rst
- source/configuration/modules/imptcp.rst
- source/configuration/modules/imrelp.rst
Duplicate labels made it past CI builds (due to each PR being separate and not rebased on master from prior merges). This commit introduces a module-specific prefix for the labels
in order to prevent conflicts.
refs #573, #574, #575
> Add doc-specific label refs for stats section

- source/conf.py
This was unintentionally left off in a recent edit to simplify the default dev build string.
> Add back project prefix to dev build string for epub builds

- source/configuration/modules/imfile.rst
- Note that the type is integer or string, with string values preferred
- Emphasized that both severity and facility are applied to messages
read from the specified file (previously emphasized "lines read")
- Add "see also" for additional Facility and Severity info
by way of Wikipedia Syslog page
- Update default column in both tables to use textual version
- corrected default for Facility parameter
closes rsyslog/rsyslog-doc#583
> imfile: Update facility and severity parameters

- source/configuration/modules/imfile.rst
The previous wording was found to be confusing in comparison with how the Facility and Severity parameters are described. Here similar emphasis has been added to stress that the
tag is set for messages read from the file.
closes rsyslog/rsyslog-doc#582
> imfile: Clarify behavior of Tag parameter

- source/configuration/modules/omfwd.rst
Used to say "ActionForwardDefaultTemplateName". Which does not work.
Now it agrees with: http://www.rsyslog.com/doc/v8-stable/configuration/action/index.html
> Fix reference to ActionForwardDefaultTemplate in omfwd.rst

- source/configuration/modules/imuxsock.rst
The type for this parameter was mislabeled. This commit changes the type to match the type specified in the [source file](https://github.com/rsyslog/rsyslog/blob/a11719a3bcae526d016a7d71d2d791692d187422/plugins/imuxsock/imuxsock.c#L257
):
```c
{ "syssock.name", eCmdHdlrGetWord, 0 },
```
Credit: @PascalWithopf for setting me straight on the specific types supported and where to find/confirm those values.
> Fix SysSock.Name parameter type

- source/configuration/modules/imuxsock.rst
The goal is to help prevent conflicts with label references used in other documents (AFAIK, Sphinx labels are global).
closes rsyslog/rsyslog-doc#627
> imuxsock: Update label refs to use module prefix

- source/configuration/filters.rst
To see a list of properties, one has to follow the link from the Property Replacement page to get to the "rsyslog Properties" page. Might as well just link directly there from here. I imagine this may have happened becasue the rsyslog Properties didn't used to be a separate page?
> Link directly to properties documentation

- source/rainerscript/include.rst
- Add subsection headers
- Add notes/warning
- Note that this object deprecates the obsolete $IncludeConfig
directive.
- Add standard "parameter names are case-insensitive" remark
- Tweak examples to use code highlighting, include notes
regarding whether files are required
closes rsyslog/rsyslog-doc#590
---
@davidelang @PascalWithopf 
See anything here out of place?
Here is what the doc changes looks like with the default theme:
http://rsyslog.whyaskwhy.org/i590-include-object-updates/rainerscript/include.html
> include(): Add section headers, formatting tweaks

- source/configuration/sysklogd_format.rst
I'm not an RST man, but this seemed like an easy fix.
> Render sysklogd examples as <pre> or the like

- source/configuration/actions.rst
Attempt to clarify the language for how the interval increases over time based off of feedback from @nohararc on rsyslog/rsyslog-doc#625.
Further work needs to be done to make clear the default value for all parameters, but that is outside the scope of this change.
> Clarify how action.resumeInterval increases over time

- source/rainerscript/queue_parameters.rst
Without enabling the option, disk-assisted queue functionality is not available.
- Credit to  @davidelang for clarifying this.
- See also: "Understanding rsyslog Queues"
closes rsyslog/rsyslog-doc#611
> queue parameters: State need for queue.filename

- source/configuration/sysklogd_format.rst
- adjust header levels
- add newline near 80 char mark
- code formatting on some keywords, filenames (more to do here)
- add Sphinx cross-reference manpage role to manpage refs
There is more to do, but I wanted to go ahead and apply a quick pass now while my attention was still on the doc (as part of working with another PR).
> "basic" format doc tweaks: formatting, headers

- source/rainerscript/configuration_objects.rst
Two cases where "enabled" was used instead of "enable".
> Fix typos in config.enabled parameter name

- source/rainerscript/global.rst
Remove invalid ``parser.permitSlashInHostname`` parameter, update content for ``parser.permitSlashInProgranName``.
Thanks to @lennardk for catching/reporting this issue.
closes rsyslog/rsyslog-doc#639
> global: remove invalid permitSlash parameter

- source/configuration/modules/imptcp.rst
Add the documentation for SocketBacklog parameter related to this PR:
https://github.com/rsyslog/rsyslog/pull/2561
> Add documentation for the new SocketBacklog parameter of the imptcp module

- README.md
Used the same Stack Exchange "filter" used in the main doc footer.
refs rsyslog/rsyslog-doc#624
> README: remove forum ref, add Stack Exchange refs

- source/conf_helpers.py
Most importantly, Travis CI stopped working with the old method
on 2018-04-10. In any case, the new method looks more up to the
point
> use different method to obtain commit hash

- source/configuration/modules/omfwd.rst
These options are added for omfwd bind-to-address support.
Signed-off-by: Mike Manning <mmanning@att.com>
> Add descriptions for address and ipfreebind options in omfwd

- source/configuration/modules/imklog.rst
`PermitNonKernalFacility` -> `PermitNonKernelFacility`
I copied the parameter from documentation and got error, until I fixed the typo. I even created https://github.com/rsyslog/rsyslog/issues/2685 before I recognized the typo :)
> imklog.rst: fix typo in parameter name

- source/configuration/modules/ommongodb.rst
closes #636 
I could not update the branch mentioned in #636, so I create this merge PR here. I needed to update the original PR because error codes now use array mode config parameter (which is meant for such use cases).
> Added allowed_error_codes documentation

- source/configuration/modules/mmkubernetes.rst
filename rules use field container_name_and_id
see also:
https://github.com/rsyslog/rsyslog/pull/2812
> fix rules to use container_name_and_id

- source/configuration/modules/imfile.rst
Now it is clear from doc what to expect there.
This is related to rsyslog/rsyslog/pull/2749 however the behavior is there even without it.
> Added note for symlink in filename imfile metadata

- source/configuration/modules/mmkubernetes.rst
The pod_name field match in the filename rule must include
everything up to the first _, including dots.
see https://github.com/rsyslog/rsyslog/pull/2824
> fix pod_name field match in filename rule - everything up to _

- source/configuration/modules/ommysql.rst
I I have submitted a patch that adds the socket option to the ommysql plugin at https://github.com/rsyslog/rsyslog/pull/2784.
Submit a patch that reflects this in the reference.
> add new socket option of ommysql plugin

- source/configuration/modules/imptcp.rst
Documentation added for:
defaulttz
framingfix.cisco.asa
> imptcp: add documentation for missing parameters

- source/configuration/modules/imtcp.rst
- source/configuration/modules/imudp.rst
Introducing an option preservecase to imudp and imtcp module for managing the case of FROMHOST value.
Usage:
module(load="imudp" [preservecase="on"|"off"])
module(load="imtdp" [preservecase="on"|"off"])
If preservecase="on", FROMHOST value is handled in the case sensitive manner.
If preservecase="off", FROMHOST value is handled in the case insensitive manner.
To maintain the current behaviour, the default value of preservecase is
"on" for imtcp and "off" for imudp.
References:
https://github.com/rsyslog/rsyslog/pull/2774
https://bugzilla.redhat.com/show_bug.cgi?id=1309698
> DOC for rsyslog/pull/2774: introducing PreserveCase

- source/configuration/modules/mmkubernetes.rst
The KubernetesURL parameter is not mandatory since it has
a useful default value.
Add information about CRI-O.
Minor cleanup.
> url not required - add information about CRI-O

- source/rainerscript/queue_parameters.rst
Parameter descriptions, default values and matching Legacy parameter were added.
Page was updated to the current style.
Closes https://github.com/rsyslog/rsyslog-doc/issues/718
> Update documentation for queue parameter

- source/configuration/modules/omprog.rst
The rsyslog module interface was not designed to support modules that
can act both as transactional and non-transactional according to
a configuration parameter. The old transaction interface (incidentally)
supports this, but it is not supported by the new transaction interface.
Therefore a future change is envisaged regarding this feature, that will
likely break backwards compatibility.
> omprog: document 'useTransactions' flag as experimental

- source/conf_helpers.py
Escape the single quotes in the git log format command so that they are not interpreted literally and included with the doc title when output files are generated.
I'm assuming that the behavior is not intentional, but please feel free to reject this PR if it is.
closes rsyslog/rsyslog-doc#743
> Escape single quotes in git log command

- source/configuration/modules/omhttp.rst
The omhttp module was contributed and until now no
documentation was available.
A basic documentation is added which is far from complete.
Closes https://github.com/rsyslog/rsyslog-doc/issues/749
> omhttp: add basic documentation for contrib module

- source/rainerscript/global.rst
this existed since long, but was not documented
closes https://github.com/rsyslog/rsyslog/issues/552
> document global parser.escapeControlCharacterTab option

- source/rainerscript/global.rst
this led to errors and confusion when copy-pasting the parameter
from doc to live config.
> fixed typo in case-sensitive global() option

- source/rainerscript/functions/rs-substring.rst
The behaviour of RainerScript function substring
was documented wrong.
Closes https://github.com/rsyslog/rsyslog/issues/3344
> correct documentation of substring function

- source/configuration/modules/omclickhouse.rst
Documentation for following parameters were added
1. allowUnsignedCerts, which allows connections with
servers, without checking if the certificates are authentic.
2. healthCheckTimeout, which sets the timeout for the
availability check for the clickhouse server.
> omclickhouse: add documentation for new parameters

- source/configuration/modules/imjournal.rst
it was always there, but easy to overlook.
> imjournal: make info how to disable ratelimiting better visible

- source/configuration/modules/omrelp.rst
Doc invalidly speaks only of fingerprint authentication where both
name and fingerprint are supported. This is wrong and pretty
confusing. Looks like a regression from last update.
see also https://github.com/rsyslog/rsyslog/issues/2253
> fix omrelp TLS authentication doc

- source/configuration/modules/imfile.rst
- source/configuration/properties.rst
Add documentation about two features introduced with the AIX Port Second Phase.
- rsyslog system time property $wday,
- imfile instance parameter 'needparse'
> Aix port step2

- source/configuration/modules/mmkubernetes.rst
- source/configuration/modules/omclickhouse.rst
- source/configuration/modules/omelasticsearch.rst
- source/configuration/modules/omhttp.rst
docs for https://github.com/rsyslog/rsyslog/pull/3558
Add ability to specify the libcurl CURLOPT_SSL_VERIFYHOST
option to skip verification of the hostname in the peer cert.
WARNING: This option is insecure, and should only be used
for testing. The default value is off, meaning, the hostname
will be verified by default.
> add support for skipverifyhost

- source/configuration/modules/omkafka.rst
- messages rejected due to exceeding maximum configured message size will be
automatically dropped.
> add note to 'resubmitOnFailure' option.

- source/troubleshooting/troubleshoot.rst
... it would be better to document the switch as well, but as it
looks we currently have no place other than the man page where
this is described.
PR: https://github.com/rsyslog/rsyslog/pull/3635
> document new -o command line switch for troubleshooting

- source/configuration/sysklogd_format.rst
Before I made changes, all the 4 lines rendered wrong in both https://www.rsyslog.com/doc/v8-stable/configuration/sysklogd_format.html and the html I generated with sphnix.
Although line 27 and 104 rendered correctly in github preview, I think the html in official website should be ultimate version.
> syntax error in sysklogd_format

- source/tutorials/tls_cert_machine.rst
The command `certtool --generate-privkey --outfile key.pem --sec-param 2048` fails with the error: ```Unknown security parameter string: 2048```. This is because `--sec-param` expects only the following parameters - [low, legacy, medium, high, ultra]. It's used as an alternative to the `--bits` flag. Running with `--bits` will fix the issue and still generate a 2048 bit key.
Source: `man certtool`
> Fixed initial key generation command parameters

- source/tutorials/tls.rst
- source/tutorials/tls_cert_client.rst
- source/tutorials/tls_cert_server.rst
- source/tutorials/tls_cert_udp_relay.rst
Ref: https://github.com/rsyslog/rsyslog-doc/issues/832
> Changed port for TLS transfer in tutorials to 6514 as different default.

- source/configuration/modules/omhttp.rst
Documentation for omhttp config parameter 'checkpath' added to omhttp docs. Also fix an
unclosed double quote in restpath parameter description.
> Add 'checkpath' to omhttp configuration docs

- source/tutorials/gelf_forwarding.rst
Now gelf forwarding tutorial claims that you cannot use omwd tcp and graylog together due nullbyte as frame delimiter.
It is false. Frame Delimiter is configurable in rsyslog since 2017. https://github.com/rsyslog/rsyslog/issues/1602
Also, timestamp field in modern gelf should be number, not string. So quotes around timestamp value is against gelf standard.
This PR is fixing both issues.
> Fix gelf documentation

- source/configuration/action/rsconf1_filecreatemode.rst
use a code-block, rather than backticks, and actually indent where needed, so this example becomes clear.
> fix display of codeblock

- source/rainerscript/global.rst
In `rsyslog/runtime/glbl.c`, the parameter is defined as `reverselookup.cache.ttl.default` instead of `reverselookup.cache.default.ttl`
> Realigning doc to source code

- source/configuration/templates.rst
* `RSYSLOG_FileFormat`,
* `RSYSLOG_ForwardFormat`,
* `RSYSLOG_TraditionalFileFormat`, and
* `RSYSLOG_TraditionalForwardFormat`
all previously implied that there would be two spaces between `syslogtag` and `msg`.
> Fix up spaces in some template definitions

- source/configuration/modules/omfwd.rst
Fixes rsyslog/rsyslog#4183
Expanded docs as per discussion in above issue to reflect that RebindInterval operates on batches for TCP traffic
> Amended RebindInterval description

- source/configuration/modules/omprog.rst
After bugfix rsyslog/rsyslog#4255, the forceSingleInstance flag no
longer makes the external program instance to be spawned during rsyslog
startup.
> omprog: change in forceSingleInstance behaviour

- source/configuration/modules/imfile.rst
Wrong parameter referenced in imfile.rst for escapeLF.replacement
> Correction for escapeLF.replacement

- tools/release_build.sh
Some minor changes to make this script run on Darwin or OS X, basically sed(1) takes different args based on platform Linux vs BSD.
> Make release docs building work on Darwin / OSX

- source/configuration/modules/sigprov_ksi12.rst
On 21. October 2020 http access to download.guardtime.com will be disabled, updating links to the repository.
> Updating download.guardtime.com links to use https

- source/rainerscript/functions/rs-exists.rst
see also https://github.com/rsyslog/rsyslog/pull/4435
> document new function "exists()"

- source/configuration/modules/omfwd.rst
Adding documentation for the new rate limit option
of omfwd for rate limiting syslog messages sent to the
remote server
ratelimit.interval:
Specifies the rate-limiting interval in seconds.
Default value is 0, which turns off rate limiting.
ratelimit.burst
Specifies the rate-limiting burst in number of messages.
Reference:
https://github.com/rsyslog/rsyslog/issues/4423
https://github.com/rsyslog/rsyslog/pull/4440
Signed-off-by: Dinesh-Ramakrishnan <pr.dinesh@gmail.com>
> omfwd doc for new feature for PR4440

- source/configuration/modules/imptcp.rst
- source/configuration/modules/imtcp.rst
Missing "Server" in legacy directive of
SupportOctetCountedFraming in imtcp and imptcp.
imtcp
Wrong:   $InputTCPSupportOctetCountedFraming
Correct: $InputTCPServerSupportOctetCountedFraming
imptcp
Wrong:   $InputPTCPSupportOctetCountedFraming
Correct: $InputPTCPServerSupportOctetCountedFraming
> Fix typo in imptcp and imtcp

- source/rainerscript/global.rst
Copied global control character escaping options from legacy format to rainerscript/global doc and changed to advanced format.
> rainerscript/global.rst: control characters escaping options

- source/configuration/modules/omhttp.rst
The documentation for `lokirest` introduced in #862 inverted examples between kafkarest and the newly added lokirest.
> omhttp: update inverted examples for kafka and loki

- source/configuration/modules/omfwd.rst
Document new parameters providing the abilit to set certificate
files on a per-action basis.
see also https://github.com/rsyslog/rsyslog/pull/4653
> omfwd: document new action() parameters

- source/how2help.rst
The http://www.monitorware.com/en/syslog-enabled-products/ URL does not work, I found https://www.adiscon.com/syslog-enabled-products/ which seems to be the replacement.
> Fix link: monitorware.com -> adiscon.com

- source/configuration/modules/omfile.rst
- source/rainerscript/global.rst
While I was reading the documentation about the ```global``` directive, I discovered that ```dynafile.donotsuspend``` was accidentally added to this section. It was designed to be an ```omfile``` module parameter.
Introduced in 6b3ef17ceff9aa61f86499ad1204a47084d7c628.
> Remove dynafile.donotsuspend from global directive

- source/configuration/modules/omkafka.rst
The **DynaKey** param is available since [v8.1903](https://github.com/rsyslog/rsyslog/pull/3350), but it's not mentioned in the [document](https://www.rsyslog.com/doc/master/configuration/modules/omkafka.html#dynakey)
> omkafka: added dynaKey available version

- source/configuration/modules/ompgsql.rst
Postgres uses double single quotes `''` to escape single quotes in strings [1].
For a default postgres setup the `option.stdsql` should be used instead of `option.sql` [2].
[1] https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-STRINGS
[2] https://www.rsyslog.com/doc/v8-stable/configuration/templates.html#options
> ompgsql: Use option.stdsql instead of option.sql in examples

- source/configuration/templates.rst
This was lost by some doc update.
Thanks to David Lang for pointing this out.
@davidelang I would appreciate if you could have a look at the PR.
> add description for legacy template format

- source/configuration/sysklogd_format.rst
4x`\` results in the double backslash in the docs
> fix: backslash escape

- source/configuration/modules/imtcp.rst
- source/configuration/modules/omfwd.rst
- source/rainerscript/global.rst
- add imtcp/omfwd streamDriver.CRLFile parameter
- and global defaultNetstreamDriverCRLFile parameter
closes: https://github.com/rsyslog/rsyslog-doc/issues/1011
> Add doc for TLS CRL (Certificate revocation list) List Parameters

- source/configuration/modules/imhiredis.rst
imhiredis dequeue batch size for redis pipelining was previously hardcoded to 10. 
This change allows to set the size of the batch via the "batchsize" parameter of the imhiredis module.
> Add the "batchsize" parameter to the imhiredis module.

- source/configuration/modules/imudp.rst
Proberly leftover from german msword editor.
closes: https://github.com/rsyslog/rsyslog-doc/issues/1038
> Replaced invalid quote character

- source/configuration/modules/omprog.rst
The documentation does not explicitly mention, where should users place their binaries that will be executed by the omprog module. Whilst rsyslog does not really care where these files are located as far as permission and ownership are fine, there are many security hardening utilities in the wild that consider this as an important aspect.
From Filesystem Hierarchy Standard point of view, definition of /usr/libexec: Binaries run by other programs that are not intended to be executed directly by users or shell scripts (optional).
My goal is to have a unified location for external programs.
What do you think?
See https://github.com/rsyslog/rsyslog/issues/5293
> omprog: Recommend libexec directory for binaries

- source/rainerscript/global.rst
closes: https://github.com/rsyslog/rsyslog-doc/issues/1052
see also: https://github.com/rsyslog/rsyslog/pull/5371
> Add doc for global parameter defaultopensslengine

- source/configuration/cryprov_ossl.rst
- source/configuration/index.rst
- source/configuration/modules/omfile.rst
Add documentation for the new `ossl` crypto provider.
Related to: https://github.com/rsyslog/rsyslog/pull/5382
> New log crypto provider: ossl

- source/configuration/modules/omhttp.rst
> fix omhttp.rst broken ref 

- source/rainerscript/queue_parameters.rst
According to https://github.com/rsyslog/rsyslog/blob/master/runtime/queue.c#L3334 , the default value of `queue.discardMark` is 98% of the overall queue size. This part of the doc has not been updated since the actual patch took place.
> Correct queue.discardMark default value

- source/configuration/modules/imptcp.rst
Enhanced the description of the SocketBacklog parameter to clarify its purpose, usage scenarios, and interaction with system-wide kernel settings. Updated the default value to reflect recent changes, providing more accurate and useful information for users.
see also: https://github.com/rsyslog/rsyslog/pull/5537
> Improve documentation for SocketBacklog parameter

- source/compatibility/v3compatibility.rst
- source/concepts/queues.rst
- source/configuration/global/options/rsconf1_abortonuncleanconfig.rst
- source/configuration/modules/imfile.rst
- source/configuration/modules/imhiredis.rst
- source/configuration/modules/imhttp.rst
- source/configuration/modules/imptcp.rst
- source/configuration/modules/imtuxedoulog.rst
- source/configuration/modules/imudp.rst
- source/configuration/modules/mmrfc5424addhmac.rst
- source/configuration/modules/omclickhouse.rst
- source/configuration/modules/omelasticsearch.rst
- source/configuration/modules/ommail.rst
- source/configuration/modules/ompipe.rst
- source/configuration/output_channels.rst
- source/configuration/rsyslog-example.conf
- source/configuration/sysklogd_format.rst
- source/configuration/templates.rst
- source/configuration/timezone.rst
- source/development/dev_queue.rst
- source/development/generic_design.rst
- source/historical/stunnel.rst
- source/rainerscript/functions/mo-http_request.rst
- source/rainerscript/global.rst
- source/troubleshooting/troubleshoot.rst
- source/tutorials/database.rst
- source/tutorials/tls.rst
- source/whitepapers/syslog_protocol.rst
In most dialects of English the rule to choose _a_ vs _an_ is to listen to the first sound of the following word (as it is _spoken_): _a_ before a consonant sound, including _h_ and _y_, and _an_ before a vowel sound.
Initialisms are read as the names of the letters, and it is important to note that the names of some consonants start with a vowel sound, while the names of some vowels start with a consonant sound:
|Initial|Read as|
|---|---|
|F|_an eff_|
|H|_an aitch_ *|
|L|_an ell_|
|M|_an em_|
|N|_an en_|
|R|_an are_|
|S|_an ess_|
|U|_a you_|
|Y|_a why_|
* some dialects prefer _a haitch_, especially in Australia
> Regularize “a” vs “an” to match English phonetics

- source/configuration/modules/omjournal.rst
The regular template directive does not work with data expressions (rsyslog/rsyslog#5571) so the `subtree` template is a better fit for `omjournal` structured output.
> 2nd omjournal sample code with subtree template supporting expressions
