- source/configuration/modules/mmsnmptrapd.rst
closes https://github.com/rsyslog/rsyslog-doc/issues/112
> fixed formatting

- source/configuration/modules/omprog.rst
As a test I made some spelling changes. For me it is figuring out how github works. Please let me know if these pull requests are either wanted or unwanted.
> Some spelling changes

- source/configuration/modules/omkafka.rst
Adds documentation for rsyslog/rsyslog#186
> omkafka: Dynamic topic and auto partition updates

- source/index.rst
> Remove duplicate link to examples

- source/configuration/modules/imtcp.rst
added documentation for imtcp address bind feature.
> Added address attribute for imtcp

- README.md
> Fixed Readme: master branch is master not v8-devel

- source/concepts/ns_gtls.rst
- source/configuration/modules/mmsnmptrapd.rst
- source/configuration/modules/omlibdbi.rst
- source/configuration/modules/ommysql.rst
- source/configuration/modules/omrelp.rst
- source/tutorials/tls.rst
- source/tutorials/tls_cert_summary.rst
Submitting this against the oldest branch. There are a couple more typos in the stable-v7 branch, I'll send another PR for this in a minute.
> correct "server" mistyped at several places

- source/configuration/modules/imfile.rst
It took me a while to figure out how to access the filename data, and in my search I found other people asking the same question with no answers.
> Added line documenting how to access filename metadata value.

- source/concepts/multi_ruleset.rst
Replace some broken links which I've found in this guide!
> fixed some broken links

- source/concepts/multi_ruleset.rst
Insert :doc: infront of the links
> Links fixed

- source/configuration/modules/pmrfc3164.rst
> Changes to pmrfc3164.rst

- source/configuration/modules/omkafka.rst
Doc changes that go with: https://github.com/rsyslog/rsyslog/pull/355
> updated omkafka documentation: added parameter closeTimeout

- source/community.rst
- source/configuration/droppriv.rst
- source/free_support.rst
- source/index.rst
- source/proposals/version_naming.rst
- source/troubleshooting/troubleshoot.rst
- source/tutorials/reliable_forwarding.rst
Please accept my changes to the docs as per detailed commit messages.
> Multiple changes to v7 stable docs. 

- source/community.rst
- source/configuration/droppriv.rst
- source/free_support.rst
- source/index.rst
- source/proposals/version_naming.rst
- source/troubleshooting/troubleshoot.rst
- source/tutorials/reliable_forwarding.rst
Please accept these changes as per detailed commit messages.
> Multiple changes to V5 stable docs.

- source/community.rst
- source/configuration/droppriv.rst
- source/free_support.rst
Please accept these changes as per detailed commit messages.
> Multiple changes to master docs.

- source/configuration/modules/omfwd.rst
Documentation for rsyslog Pull-Request #493.
> Adding documentation for client side keep-alives.

- source/configuration/modules/omhiredis.rst
This PR adds initial documentation for the omhiredis output module.
> add omhiredis documentation

- source/configuration/modules/omhiredis.rst
Add a note about template mode config setting.
> omhiredis -fix doc to account for config parsing bug

- source/configuration/modules/mmanon.rst
> correct a spelling mistake

- build.sh
- release_build.sh
- source/configuration/property_replacer.rst
- source/configuration/templates.rst
I haven't tested the scripts completely, feel free to do so to make sure they work properly.
Let me know if you want something changed or done differently.
> Add info about new fixed width option and fixup scripts a bit

- source/tutorials/tls_cert_machine.rst
> Update the screen session for current version of certtool

- source/configuration/modules/imfile.rst
See also https://github.com/rsyslog/rsyslog/pull/662.
Here is a screenshot of generated page:
> Document new imfile parameter 'reopenOnTruncate'

- source/configuration/modules/omruleset.rst
- source/configuration/ruleset/rsconf1_rulesetparser.rst
Improvements for the rsyslog documentation
> Typos and minor layout changes

- source/configuration/modules/omruleset.rst
- source/configuration/ruleset/rsconf1_rulesetparser.rst
Improvements for the rsyslog v5 documentation
> Typos and minor layout changes v5

- source/configuration/modules/omruleset.rst
- source/configuration/ruleset/rsconf1_rulesetparser.rst
Improvements for the rsyslog v8 documentation
> Typos and minor layout changes v8

- source/configuration/modules/omruleset.rst
- source/configuration/ruleset/rsconf1_rulesetparser.rst
Improvements for the rsyslog v7 documentation
> Typos and minor layout changes v7

- .travis.yml
- source/_templates/layout.html
this is no longer supported or maintained.
> add warning boilderplate to dead v5 doc

- source/configuration/dyn_stats.rst
- source/configuration/index.rst
- source/configuration/lookup_tables.rst
- source/rainerscript/functions.rst
+ some formatting love to make functions page more readable
> Lookup and dyn stats documentation

- source/configuration/modules/imfile.rst
See also rsyslog/rsyslog#664.
Here is a screenshot of generated page:
> Document new imfile parameter 'trimLineOverBytes'

- source/configuration/modules/imptcp.rst
Documents https://github.com/rsyslog/rsyslog/pull/567
> imptcp processOnPoller documentation

- source/configuration/templates.rst
Documents PR https://github.com/rsyslog/rsyslog/pull/622.
> Update to reflect casesensitive template option

- source/configuration/modules/omamqp1.rst
Add configuration and used documentation for the AMQP 1.0 messaging output module.
> Documentation for the AMQP 1.0 output module

- source/configuration/properties.rst
... plus some light restructuring
> describe new set of $now-utc system properties

- source/configuration/property_replacer.rst
- source/configuration/templates.rst
see also https://github.com/rsyslog/rsyslog/issues/730
> document new UTC date conversion template options

- source/configuration/property_replacer.rst
- source/configuration/templates.rst
see also https://github.com/rsyslog/rsyslog/issues/861
> document new "compressspace" template option

- source/configuration/dyn_stats.rst
- source/rainerscript/control_structures.rst
Covers PR: https://github.com/rsyslog/rsyslog/pull/931
> Doc for dyn-stats + foreach-object PR

- source/configuration/modules/imptcp.rst
Adds documentation for existing functionality
> Docs for imptcp unix domain socket support

- source/configuration/modules/omrelp.rst
This depends on [rsyslog#1023](https://github.com/rsyslog/rsyslog/pull/1023)
> conn.timeout docs

- source/tutorials/tls_cert_server.rst
The ReStructuredText format doesn't support making text bold and italic at the same time.
See http://stackoverflow.com/a/11984833/4694621.
> Fix formatting. rst can't be both italic and bold.

- source/concepts/multi_ruleset.rst
Do not yet merge, I am verifying the wording; it may change.
> clarify implications of ruleset queues

- source/configuration/modules/imfile.rst
code will be updated with PR https://github.com/rsyslog/rsyslog/pull/1182
> imfile: document new readTimeout parameter family

- source/configuration/modules/omfwd.rst
* Update the KeepAlive parameters to match the source code.
* Original commit that set parameters https://github.com/rsyslog/rsyslog/commit/62391aaff2d80f96cc69b26dc8d91da2a52fc9c6
* Updated unit test https://github.com/rsyslog/rsyslog/commit/9d839634d9bc7db9657a502f5230d5590c704c69
> omfwd: Fix KeepAlive parameters

- source/configuration/modules/omelasticsearch.rst
Adding documentation for https://github.com/rsyslog/rsyslog/pull/1169
> Adding documentation for new maxbytes parameter

- source/configuration/modules/omelasticsearch.rst
Documentation for https://github.com/rsyslog/rsyslog/pull/1196
> Updated documentation for ha configuration of omelasticsearch

- source/rainerscript/global.rst
see also https://github.com/rsyslog/rsyslog/pull/1209
see also https://github.com/rsyslog/rsyslog/pull/1210
> describe the new 'global(environment="var=val")' parameter

- source/configuration/modules/imjournal.rst
> Fixed typo in example

- source/configuration/modules/ommongodb.rst
> Formatting issue fixing #105

- source/configuration/modules/imjournal.rst
Closes https://github.com/rsyslog/rsyslog-doc/issues/187
> Document imjournal usepidfromsystem

- source/configuration/modules/imudp.rst
see also https://github.com/rsyslog/rsyslog/pull/1306
> document new imudp max value

- source/configuration/modules/omelasticsearch.rst
see also https://github.com/rsyslog/rsyslog/pull/1307
> document removed omelasticsearch parameter

- source/development/dev_codestyle.rst
see also https://github.com/rsyslog/rsyslog/issues/1214
see also https://github.com/rsyslog/rsyslog/issues/1010
see also https://github.com/rsyslog/codestyle/issues/1
> begin to document code style

- source/rainerscript/index.rst
- source/rainerscript/rainerscript_call_indirect.rst
see also https://github.com/rsyslog/rsyslog/issues/1318
> document new "call_indirect" RainerScript statement

- source/concepts/queues.rst
Contribute for https://github.com/rsyslog/rsyslog/issues/1339
> Add documentation for recover_qi.pl script

- source/configuration/properties.rst
see also https://github.com/rsyslog/rsyslog/issues/1361
> clarify content of "programname" property

- source/configuration/properties.rst
- source/rainerscript/global.rst
see also https://github.com/rsyslog/rsyslog/issues/1365
> document new global parser.permitSlashiInProgramname option

- source/configuration/properties.rst
thanks to github user mostolog for pointing this out
> fix copy&paste error

- source/rainerscript/global.rst
According to what I learned in the thread http://lists.adiscon.net/pipermail/rsyslog/2017-February/044197.html, may I suggest this update regarding new processInternalMessages behaviour?
> Update global.rst processInternalMessages

- source/configuration/modules/omfwd.rst
Add documentation for https://github.com/rsyslog/rsyslog/pull/1458
> omfwd: add network namespace doc

- source/configuration/modules/imptcp.rst
> Docs for imptcp domain socket permissions

- source/configuration/modules/idx_output.rst
- source/configuration/modules/imtcp.rst
- source/configuration/modules/omfile.rst
- source/configuration/modules/sigprov_ksi12.rst
Created short description for the new Guardtime KSI module rsyslog-ksi-ls12 that will be available since rsyslog 8.27.
> Added the description of the Guardtime KSI module rsyslog-ksi-ls12

- source/configuration/modules/pmnull.rst
- source/index.rst
see also https://github.com/rsyslog/rsyslog/issues/1498
> pmnull: clarify use cases

- source/configuration/modules/imrelp.rst
Depends on https://github.com/rsyslog/rsyslog/pull/1525
> Document the imrelp maxDataSize config option

- source/configuration/modules/mmdblookup.rst
see also https://github.com/rsyslog/rsyslog/pull/1589
> mmdblookup: add new parameters

- source/configuration/modules/omfwd.rst
see also https://github.com/rsyslog/rsyslog/issues/1602
see also https://github.com/rsyslog/rsyslog/pull/1610
> omfwd: add description for new TCP_frameDelimiter parameter

- source/configuration/modules/imfile.rst
- source/configuration/modules/mmjsonparse.rst
- source/configuration/property_replacer.rst
- source/configuration/ruleset/rsconf1_rulesetparser.rst
- source/rainerscript/functions.rst
- source/rainerscript/lookup_tables.rst
- source/rainerscript/variable_property_types.rst
Hello
this PR proposes a bunch of improvements and some others small fixes.
dud
> Various doc improvements

- source/configuration/modules/imptcp.rst
requires https://github.com/rsyslog/rsyslog/pull/1669
> imptcp: add description of multiLine parameter

- source/configuration/modules/impstats.rst
requires https://github.com/rsyslog/rsyslog/pull/1667
> impstats: document new stats counter

- README.md
- source/configuration/droppriv.rst
- source/configuration/modules/mmexternal.rst
- source/configuration/modules/omhdfs.rst
- source/configuration/modules/omprog.rst
- source/configuration/modules/omuxsock.rst
- source/rainerscript/global.rst
see also https://github.com/rsyslog/rsyslog/pull/1705
also fixed a formatting problem caused by the new sphinx-version.
> Add description for debug.file and debug.whitelist parameters

- source/rainerscript/functions.rst
see also https://github.com/rsyslog/rsyslog/pull/1712
> rainerscript: add description of functions rtrim and ltrim

- source/configuration/lookup_tables.rst
- source/configuration/templates.rst
- source/history.rst
- source/rainerscript/global.rst
- source/whitepapers/queues_analogy.rst
I'm new to making contributions via GitHub, so please let me know if I'm going about this correctly.
Thanks.
> Various typo and wording tweaks

- source/configuration/modules/mmanon.rst
see also https://github.com/rsyslog/rsyslog/pull/1739
> update documentation for the mmanon module

- source/concepts/queues.rst
- source/configuration/global/index.rst
- source/configuration/global/options/rsconf1_mainmsgqueuesize.rst
- source/rainerscript/queue_parameters.rst
> fixed queue default values

- source/configuration/global/index.rst
- source/configuration/global/options/rsconf1_mainmsgqueuesize.rst
- source/rainerscript/queue_parameters.rst
many defaults are dynamically calculated
> fix specified defaults to actual value

- source/compatibility/v8compatibility.rst
- source/concepts/multi_ruleset.rst
- source/concepts/queues.rst
- source/configuration/basic_structure.rst
- source/configuration/global/options/rsconf1_generateconfiggraph.rst
- source/configuration/global/options/rsconf1_maxopenfiles.rst
- source/configuration/lookup_tables.rst
- source/configuration/modules/idx_library.rst
- source/configuration/modules/impstats.rst
- source/configuration/modules/mmfields.rst
- source/configuration/modules/ompipe.rst
- source/configuration/properties.rst
- source/configuration/ruleset/rsconf1_rulesetparser.rst
- source/configuration/templates.rst
- source/development/config_data_model.rst
- source/development/dev_oplugins.rst
- source/features.rst
- source/free_support.rst
- source/installation/build_from_repo.rst
- source/installation/install_from_source.rst
- source/installation/packages.rst
- source/rainerscript/control_structures.rst
- source/rainerscript/functions.rst
- source/rainerscript/variable_property_types.rst
- source/troubleshooting/debug.rst
- source/troubleshooting/selinux.rst
- source/troubleshooting/troubleshoot.rst
- source/whitepapers/queues_analogy.rst
I'm going ahead and submitting the PR, but I've got some more changes to include on this PR (via the referenced branch). Still getting the hang of Git, GitHub and submitting PRs, so please let me know if I need to go about this differently.
> Various typo fixes and grammar tweaks

- source/configuration/modules/mmanon.rst
see also https://github.com/rsyslog/rsyslog/pull/1953
> mmanon: add documentation for IPv6 with embedded IPv4

- source/configuration/modules/mmjsonparse.rst
see also https://github.com/rsyslog/rsyslog/issues/2011
> mmjsonparse: add missing description for some parameters

- source/configuration/modules/omelasticsearch.rst
Include new parameters `pipelineName` and `dynPipelineName` added by rsyslog/rsyslog#1914 and rsyslog/rsyslog#1862
> update omelasticsearch according to #1914

- source/configuration/modules/mmjsonparse.rst
Looks like a small typo was included in #393.
> Fix typo in CEE cookie name

- source/development/config_data_model.rst
- Attempted to emphasize where a real queue is needed
- Added references to Queues concept and whitepaper docs
refs rsyslog/rsyslog-doc#383
> Updated details for ruleset's queue object

- README.md
Still more work to do on rsyslog/rsyslog-doc#405, will continue that work from another branch later when I have more time.
> Update README doc: links, old info, current stable branch

- source/conf.py
I wasn't completely sure about some of the values, so let me know if you'd like some changes and I'll work those in.
closes rsyslog/rsyslog-doc#408
> Add general author option, epub specific options to build configuration file

- source/configuration/modules/ompgsql.rst
> update postgres output documentation in preparation of the 8.32 release

- source/rainerscript/functions.rst
see also https://github.com/rsyslog/rsyslog/pull/2188
> add doc for previous_action_suspended() script function

- source/rainerscript/functions.rst
see also https://github.com/rsyslog/rsyslog/pull/2198
> add description for parse_json() script function

- source/rainerscript/functions.rst
function.
see also: https://github.com/rsyslog/rsyslog/pull/2191
> rainerscript: add documentation for substring

- source/conf.py
- source/configuration/modules/imuxsock.rst
Behavior for systemd systems explicitely described after source
code review.
see also https://github.com/rsyslog/rsyslog-doc/issues/397
> imuxsock: update with details re systemd and systemd journal

- README.md
closes rsyslog/rsyslog-doc#405
> Update README file: cover building epub, refresh URLs, list assumptions, use virtualenv and local package installs

- source/rainerscript/global.rst
Add details for new global parameter using commit log notes for the feature introduced on rsyslog/rsyslog#2236
closes rsyslog/rsyslog-doc#441
> global: Add entry for "dynafile.donotsuspend" parameter

- source/configuration/conf_formats.rst
@rgerhards I wasn't sure if you saw my notes on that PR asking where I should push my changes (a new branch, your branch, ...) so I went ahead and opted to push to a new branch on my end and submit this PR for your review.
Going forward, what would be the most useful approach for me to use to illustrate suggested changes against one of your PRs? We've both used in-line code reviews, but I am under the impression that those are mainly for short bits of feedback and not counter proposals for content changes?
refs rsyslog/rsyslog-doc#417
> Hand merge existing work on PR 417

- source/configuration/global/index.rst
closes rsyslog/rsyslog-doc#453
refs rsyslog/rsyslog#2280, rsyslog/rsyslog#2282
> Remove OptimizeForUniprocessor coverage

- source/configuration/modules/pmlastmsg.rst
refs rsyslog/rsyslog-doc#452, rsyslog/rsyslog-doc#455
> pmlastmsg: Fix links, prune copyright

- source/rainerscript/functions.rst
see also https://github.com/rsyslog/rsyslog/pull/2242
> rscript: add documentation for int2Hex function

- source/tutorials/tls.rst
closes https://github.com/rsyslog/rsyslog/issues/1894
> remove no-longer-existing limitation in TLS doc

- source/configuration/modules/omhiredis.rst
see also https://github.com/rsyslog/rsyslog/pull/2305
> omhiredis: add documentation for userpush parameter

- source/configuration/modules/imfile.rst
see also https://github.com/rsyslog/rsyslog/pull/2344
> imfile: add doc for sortfiles parameter

- source/configuration/modules/mmpstrucdata.rst
see also https://github.com/rsyslog/rsyslog/pull/2364
> document new mmpstrucdata parameter "sd_name.lowercase"

- source/configuration/actions.rst
see also https://github.com/rsyslog/rsyslog/pull/2361
> document new action parameter "action.errorfile"

- README.md
Inspired by a conversation on the mailing list.
> Update README with brief contribution steps

- source/configuration/actions.rst
Add version where action.errorfile parameter first appeared
refs rsyslog/rsyslog-doc#481
> action.errorfile: Add versionadded directive

- release_build.sh
now that we have the version argument, we can directly
create the right tarball name ;-)
> release_build: create tarball with versioned name

- source/rainerscript/global.rst
see also https://github.com/rsyslog/rsyslog/pull/2369
see also https://github.com/rsyslog/rsyslog/issues/533
> document new global parameter shutdown.enable.ctl-c

- .travis.yml
- requirements.txt
With some of the features I am working with we may need to get specific with the package requirments. This is a prototype to make sure that I have the syntax right before merging to master.
> Create requirements.txt, update travis conf

- source/configuration/modules/omkafka.rst
It took a while to figure out how to do this, so document the findings
for everyone.
> Explain use of key to get random-consistent partition choice

- source/rainerscript/constant_strings.rst
... and also the others, as they were not yet described
see also https://github.com/rsyslog/rsyslog/pull/2419
> describe new backtick string format

- source/troubleshooting/troubleshoot.rst
closes https://github.com/rsyslog/rsyslog-doc/issues/530
> clarify values for -N rsyslogd command line option

- source/rainerscript/configuration_objects.rst
see also https://github.com/rsyslog/rsyslog/pull/2433
> document 8.33 config object parameter "config.enable"

- source/development/generic_design.rst
- source/historical/module_devel.rst
- source/historical/php_syslog_ng.rst
- source/historical/stunnel.rst
- source/installation/install_from_source.rst
- source/tutorials/database.rst
- source/tutorials/recording_pri.rst
- source/tutorials/tls_cert_summary.rst
updated contributor URLs and removed content that no longer
is useful
> cleanup some contributed pages

- CONTRIBUTING.md
this policy is in effect for several years now, but was
never formally written down. So far, it has been communicated
oral, via private mails, the mailing list ... and probably some
other hard to track channels. Now let's officiall "publish" it.
> document contribution policy

- source/configuration/templates.rst
see also https://github.com/rsyslog/rsyslog/pull/2475
> describe new json-generation template methods

- source/configuration/modules/imfile.rst
> imfile: rewrite documentation

- source/configuration/modules/imkafka.rst
> imkafka: rewrite documentation

- source/configuration/modules/imkmsg.rst
> imkmsg: rewrite documentation

- source/configuration/modules/impstats.rst
> impstats: rewrite documentation

- source/configuration/modules/imptcp.rst
> imptcp: rewrite documentation

- source/configuration/modules/imrelp.rst
> imrelp: rewrite documentation

- source/rainerscript/global.rst
see https://github.com/rsyslog/rsyslog/issues/2482
> fix invalid parameter name

- source/configuration/modules/im3195.rst
> im3195: rewrite documentation

- source/configuration/modules/omamqp1.rst
> omamqp1: rewrite documentation

- source/configuration/modules/imtcp.rst
> imtcp: rewrite documentation

- source/configuration/modules/imsolaris.rst
> imsolaris: rewrite documentation

- source/configuration/modules/omelasticsearch.rst
> omelasticsearch: rewrite documentation

- source/configuration/modules/imudp.rst
> imudp: rewrite documentation

- source/configuration/modules/omfile.rst
Module documentation was rewritten in the new style
> omfile: rewrite documentation

- source/configuration/modules/imgssapi.rst
> imgssapi: rewrite documentation

- source/configuration/modules/ommysql.rst
> ommysql: rewrite documentation

- source/configuration/modules/ommail.rst
> ommail: rewrite documentation

- source/configuration/modules/omhiredis.rst
> omhiredis: rewrite documentation

- source/configuration/modules/omhdfs.rst
> omhdfs: rewrite documentation

- source/configuration/modules/ompgsql.rst
> ompgsql: rewrite documentation

- source/configuration/modules/omjournal.rst
> omjournal: rewrite documentation

- source/configuration/modules/omlibdbi.rst
> omlibdbi: rewrite documentation

- source/configuration/modules/omhttpfs.rst
> omhttpfs: rewrite documentation

- source/configuration/modules/omkafka.rst
> omkafka: rewrite documentation

- source/conf.py
2 'automating' were used together, removed 1 .
> fixed a typing error.

- source/configuration/modules/ommongodb.rst
> ommongodb: rewrite documentation

- source/rainerscript/functions.rst
also add description of http_request function
> add documentation for the change to module and built-in functions

- source/includes/footer.inc.rst
- source/includes/substitution_definitions.inc.rst
This is per a recent mailing list conversation.
closes rsyslog/rsyslog-doc#622
> Update references to support resources

- source/configuration/modules/mmkubernetes.rst
- source/configuration/modules/omelasticsearch.rst
documentation for mmkubernetes
> documentation for mmkubernetes

- source/rainerscript/functions/idx_built-in_functions.rst
- source/rainerscript/functions/rs-int2hex.rst
- source/rainerscript/functions/rs-re_extract.rst
- source/rainerscript/functions/rs-re_match.rst
- source/rainerscript/functions/rs-substring.rst
Improvement ideas of following comment were added.
https://github.com/rsyslog/rsyslog-doc/pull/637#issuecomment-376973382
> rainerscript functions: add information

- source/configuration/modules/omrelp.rst
documentation was rewritten in the new style.
> omrelp: rewrite documentation

- source/configuration/modules/imklog.rst
Document imklog ratelimiting to accompany
rsyslog PR 2499
> Document imklog ratelimit

- source/configuration/modules/imrelp.rst
description for parameter maxDataSize was adjusted
> imrelp: add doc for parameter oversizeMode

- source/configuration/modules/imudp.rst
introduced in 8.35.0,
see also https://github.com/rsyslog/rsyslog/pull/2690
> imudp: document new stats counter "disallowed"

- source/rainerscript/global.rst
new global parameter:
- oversizemsg.report
- oversizemsg.errorfile
- oversizemsg.input.mode
> documentation for new global parameter added

- source/configuration/modules/omprog.rst
omprog documentation was rewritten in the new style.
> omprog: rewrite documentation

- source/configuration/modules/omruleset.rst
documentation was rewritten in the new style
> omruleset: rewrite documentation

- source/configuration/modules/imjournal.rst
closes https://github.com/rsyslog/rsyslog-doc/issues/670
> imjournal: add doc for new statistics counter

- source/configuration/modules/omsnmp.rst
Documentation was rewritten in the new style.
> omsnmp: rewrite documentation

- source/configuration/modules/omudpspoof.rst
documentation was rewritten in the new style
> omudpspoof: rewrite documentation

- source/configuration/modules/omusrmsg.rst
> omusrmsg: rewrite documentation

- source/configuration/modules/imrelp.rst
closes https://github.com/rsyslog/rsyslog-doc/issues/669
> imrelp: correct format for parameter description

- source/configuration/modules/omuxsock.rst
> omuxsock: rewrite documentation

- source/configuration/modules/sigprov_ksi12.rst
Documentation was rewritten in the new style.
> Keyless Signature Infrastructure Provider doc rewritten

- source/configuration/modules/pmlastmsg.rst
> pmlastmsg: rewrite documentation

- source/configuration/modules/omelasticsearch.rst
This is the documentation for https://github.com/rsyslog/rsyslog/pull/2733
> add writeoperation, retryfailures, retryruleset - and retry configuration

- source/configuration/modules/mmexternal.rst
> mmexternal: rewrite documentation

- source/configuration/modules/pmrfc3164.rst
Documentation was rewritten in the new style.
> pmrfc3164: rewrite documentation

- source/configuration/modules/pmnull.rst
> pmnull: rewrite documentation

- source/configuration/modules/imptcp.rst
> imptcp: document new framing.delimiter.regex parameter

- source/configuration/modules/imjournal.rst
Documentation for PR: https://github.com/rsyslog/rsyslog/pull/2775
> imjournal: documentation for additional impstats counters

- source/configuration/global/options/rsconf1_abortonuncleanconfig.rst
- source/rainerscript/global.rst
The parameter abortOnUncleanConfig is now also
available in the new config style.
> doc for new global parameter abortOnUncleanConfig

- source/configuration/global/options/rsconf1_abortonuncleanconfig.rst
fix wording so we can merge https://github.com/rsyslog/rsyslog/pull/2803
> give better cross-reference for old to new style param

- source/rainerscript/constant_strings.rst
see also https://github.com/rsyslog/rsyslog/pull/2820
> document new backticks functionality (config strings)

- source/configuration/modules/impstats.rst
Avoid user confusion as per https://github.com/rsyslog/rsyslog/issues/2821.
> Clarification to help avoid issue #2821 logged in core rsyslog repo

- source/rainerscript/global.rst
see also https://github.com/rsyslog/rsyslog/pull/2865
> document new globale parameter inputs.timeout.shutdown

- source/configuration/modules/imjournal.rst
this is documentation for rsyslog/rsyslog#2543
> Added WorkAroundJournalBug parameter

- source/configuration/modules/omprog.rst
The forceSingleInstance flag is currently not working (see rsyslog/rsyslog#2813).
Added a warning explaining this, along with a workaround.
The stdout/stderr of the external program are currently assigned in an
unpredictable way (see rsyslog/rsyslog#2787). Added a warning explaining this.
> omprog: document issues with forceSingleInstance and output redirection

- source/configuration/modules/omelasticsearch.rst
Write all of the original request metadata fields to `$.omes` for
the retry, if present. This may include all of the following:
_index, _type, _id, _parent, pipeline
This is in addition to the fields from the response. If the same
field name exists in the request metadata and the response, the
field from the request will be used, in order to facilitate
retrying the exact same request.
https://github.com/rsyslog/rsyslog/pull/2906
> write all header metadata to omes for retries

- source/configuration/modules/imptcp.rst
see https://github.com/rsyslog/rsyslog/pull/2964
> imptcp: documentation for parameter ListenPortFileName

- source/rainerscript/queue_parameters.rst
closes https://github.com/rsyslog/rsyslog/issues/2976
> fix queue.timeoutshutdown description

- source/configuration/modules/imfile.rst
add documentation for endmsg.regex
for https://github.com/rsyslog/rsyslog/pull/3014
> imfile - add documentation for endmsg.regex

- source/configuration/modules/imkafka.rst
Add document of parameter ParseHostname in imkafka.
> Add document of parameter ParseHostname in imkafka.

- source/configuration/modules/omprog.rst
Documents rsyslog/rsyslog#2945
Documents rsyslog/rsyslog#2983
Documents rsyslog/rsyslog#3009
> omprog: document improvements in v8.38

- source/configuration/modules/mmkubernetes.rst
Document the new error handling flows and the new statistics counters. This
is for https://github.com/rsyslog/rsyslog/pull/2962
> mmkubertnetes: action fails preparation cycle if kubernetes API destroys resource during bootup sequence

- source/configuration/modules/imrelp.rst
See implementation in rsyslog/rsyslog#2849
> imrelp: document bind address option

- source/configuration/templates.rst
List of reserved templates was added.
Closes https://github.com/rsyslog/rsyslog-doc/issues/653
> add all built-in templates to the documentation

- source/configuration/templates.rst
Hi,
I'm not 100% sure this is the right way to fix the second sentence.
> templates: fix typo and slightly reword

- source/rainerscript/global.rst
see also https://github.com/rsyslog/rsyslog/pull/3177
> describe new global parameter "operatingStateFile"

- source/concepts/queues.rst
closes https://github.com/rsyslog/rsyslog-doc/issues/655
> fix outdated doc

- source/rainerscript/global.rst
Parameter added in 8.26.0 by https://github.com/rsyslog/rsyslog/pull/1447
> Add doc for global() umask

- source/configuration/modules/omfwd.rst
Couldn't find anywhere in the docs what the two option words were.
> Add the TCP_Framing options ("traditional" or "octet-counted")

- source/configuration/modules/mmkubernetes.rst
doc changes for https://github.com/rsyslog/rsyslog/pull/3345
> mmkubernetes: docs for new sslpartialchain parameter

- source/development/dev_codestyle.rst
You can squash these commits when you merge.
> dev_codestyle.rst: fix typos

- source/configuration/modules/omclickhouse.rst
See https://github.com/rsyslog/rsyslog/issues/2272
> add documentation for module omclickhouse

- source/rainerscript/global.rst
Documents rsyslog/rsyslog#3328
> document new global setting 'reportChildProcessExits'

- source/configuration/actions.rst
see also https://github.com/rsyslog/rsyslog/pull/3403
> describe new paramter action.resumeIntervalMax

- source/rainerscript/queue_parameters.rst
see also https://github.com/rsyslog/rsyslog/pull/3414
> update action queue.timeoutshutdown default

- source/conf.py
Copyright message updated from 2017 to 2019
> Copyright message updated

- source/configuration/templates.rst
Typo  in RSYSLOG_DebugFormat fixed
> Typo fixed

- source/configuration/modules/omhttp.rst
Documentation for omhttp updates and changes.
> omhttp: doc updates.

- source/configuration/modules/omkafka.rst
Documentation changes for https://github.com/rsyslog/rsyslog/pull/3350
> omkafka dynaKey documentation

- source/configuration/modules/mmtaghostname.rst
>  document mmtaghostname

- source/configuration/modules/omelasticsearch.rst
Documentation for PR
https://github.com/rsyslog/rsyslog/pull/3557
> omelasticsearch: add support for reconnectafter

- source/configuration/modules/imdocker.rst
> contrib_imdocker

- source/configuration/modules/mmkubernetes.rst
for https://github.com/rsyslog/rsyslog/pull/3539
> document new parameters and stat counters

- source/configuration/modules/improg
- source/configuration/modules/improg.rst
Documentation of improg. Input module for external program
> contrib_improg

- source/index.rst
This is a first try to submit a patch request and to get familiar with sphinx customs. Please at least verify that I got the links right before merging.
> add a paragraph encouraging contributions

- source/configuration/modules/pmdb2diag.rst
> Contrib_pmdb2diag

- source/configuration/modules/omelasticsearch.rst
docs for https://github.com/rsyslog/rsyslog/pull/3577
> omelasticsearch - retry: set rawmsg to data from original request

- source/rainerscript/global.rst
see also https://github.com/rsyslog/rsyslog/pull/3616
> document new global parameter reverselookup.cache.default.ttl

- source/rainerscript/global.rst
this was forgotten to do alongside the release
closes https://github.com/rsyslog/rsyslog-doc/issues/763
> document new 8.1901.0 global default parameters

- source/configuration/modules/imfile.rst
* had too much detail on implementation internals
* was not fully up to date on module code
see also https://github.com/rsyslog/rsyslog/issues/3204
> fix imfile state file descripton

- source/configuration/modules/imfile.rst
see also https://github.com/rsyslog/rsyslog/pull/3632
> document new statefile.directory imfile module parameter

- source/configuration/modules/omfile.rst
see also https://github.com/rsyslog/rsyslog/pull/3637
> omfile: flush on TX end behaviour and dynafiles

- source/tutorials/tls.rst
- source/tutorials/tls_cert_client.rst
- source/tutorials/tls_cert_machine.rst
- source/tutorials/tls_cert_server.rst
- source/tutorials/tls_cert_udp_relay.rst
Changed configuration samples in the tls tutorial from old legacy style configuration to current style configuration.
> Reworked configuration samples in tls tutorial to current style

- source/rainerscript/queue_parameters.rst
see also https://github.com/rsyslog/rsyslog/pull/3642
> document new queue.lightDelayMark special value 0

- source/rainerscript/global.rst
see also https://github.com/rsyslog/rsyslog/pull/3654
> document new internalmsg.severity global parameter

- source/rainerscript/global.rst
see also https://github.com/rsyslog/rsyslog/pull/3657
> document global default parameters for action and ruleset queues

- source/configuration/global/options/rsconf1_includeconfig.rst
The indentation created undesired headings in the quote, making it difficult to read. This PR fixes the formatting.
> Fix formatting of quote

- source/configuration/modules/immark.rst
> create immark documentation

- source/configuration/modules/imtcp.rst
see also https://github.com/rsyslog/rsyslog/pull/3754
> document new imtcp parameter "listenPortFileName"

- source/configuration/modules/imjournal.rst
> Documetation for new 'fsync' imjournal option

- source/configuration/modules/mmdarwin.rst
Add mmdarwin documentation to the project.
The mmdarwin pull request is [here](https://github.com/rsyslog/rsyslog/pull/3556).
> Add mmdarwin documentation

- source/concepts/ns_gtls.rst
- source/configuration/modules/imtcp.rst
- source/configuration/modules/omfwd.rst
Doc content for rsyslog/rsyslog#3845
> Documentation of stricter GTLS options

- source/configuration/converting_to_new_format.rst
- source/configuration/index.rst
Signed-off-by: Rainer Gerhards <rgerhards@adiscon.com>
> add some instruction for converting old conf files to new format

- source/configuration/modules/omfile.rst
ioBufferSize="64k" flushOnTXEnd="off" asyncWriting="off"
> veryRobustZip notes to maintain compression factor

- source/configuration/modules/imjournal.rst
This is to go with rsyslog/rsyslog/pull/3878 code PR.
> imjournal doc update

- source/tutorials/failover_syslog_server.rst
see also https://github.com/rsyslog/rsyslog/issues/3961#issuecomment-553304576
> improve failover documentation  

- source/configuration/modules/imfile.rst
see also https://github.com/rsyslog/rsyslog/pull/3964
> imfile: document new parameter escapeLF.replacement

- source/rainerscript/global.rst
closes https://github.com/rsyslog/rsyslog-doc/issues/863
> add missing doc for global param

- source/configuration/modules/omsnmp.rst
see also: https://github.com/rsyslog/rsyslog/pull/3994
> omdnmp: add doc entry for new Snmpv1DynSource parameter.

- source/configuration/actions.rst
As per the subject - `achieve` not `archive`.
> A very small wording typo

- source/configuration/modules/omhiredis.rst
- added set mode
- added expiration parameter
- added example(s) for set, with and without expiration
- updated examples for clarity
> omhiredis: add 'set' mode, 'expiration' parameter, update examples

- source/configuration/modules/omclickhouse.rst
related to https://github.com/rsyslog/rsyslog/pull/4057 main repo PR
> omclickhouse: Documetation for new 'timeout' option

- source/configuration/modules/imuxsock.rst
Thanks to Tim Scanlon for alerting me.
> remove outdated info

- source/configuration/modules/imtcp.rst
- source/configuration/modules/omfwd.rst
See also
https://github.com/rsyslog/rsyslog/pull/4091
> imtcp / omfwd doc for new feature for PR4091

- source/configuration/filters.rst
Noticed while I was reading some docs :smile_cat:
> Minor grammar correction

- source/rainerscript/global.rst
see also https://github.com/rsyslog/rsyslog/pull/4166
> document new parameter "security.abortOnIDResoultionFail"

- source/configuration/modules/imfile.rst
Related to https://github.com/rsyslog/rsyslog/pull/4160
> Add documentation for MaxBytesPerMinute and MaxLinesPerMinute

- source/configuration/modules/omhttp.rst
Documenting the new httpheaders parameter proposed on rsyslog/rsyslog PR https://github.com/rsyslog/rsyslog/pull/4219
> omhttp: adding documentation for new httpheaders parameter

- source/configuration/modules/ompipe.rst
This documentation patch goes along with rsyslog github pull
request rsyslog/rsyslog#4136.
> ompipe: describe the tryResumeReopen option (action)

- source/configuration/modules/imfile.rst
see also https://github.com/rsyslog/rsyslog/pull/4031
> imfile: add new parameter "persistStateAfterSubmission"

- source/configuration/modules/impcap.rst
First version of Impcap documentation, associated with rsyslog/rsyslog#3988
> Impcap documentation

- source/rainerscript/global.rst
see also https://github.com/rsyslog/rsyslog/pull/4069
> document new global parameter shutdown.queue.doublesize

- source/configuration/modules/omelasticsearch.rst
This goes along with rsyslog/rsyslog#4368
> omelasticsearch: describe option skipPipelineIfEmpty

- source/rainerscript/functions/rs-cnum.rst
closes https://github.com/rsyslog/rsyslog-doc/issues/905
> clarify rules for cnum() function

- source/configuration/modules/imhttp.rst
documentation for imhttp input module PR: https://github.com/rsyslog/rsyslog/pull/4301
> Add documentation for imhttp input module

- source/configuration/properties.rst
see also https://github.com/rsyslog/rsyslog/pull/4456
> document new $now-unixtimestamp property

- source/configuration/modules/omfwd.rst
see also https://github.com/rsyslog/rsyslog/pull/4525
> document new statistics counter

- source/configuration/modules/omfwd.rst
Add documentation for ConErrSkip option.
> Documentation for ConErrSkip option.

- source/rainerscript/functions/mo-unflatten.rst
This goes along with pull-request rsyslog/rsyslog#4551:
fmunflatten: rscript function to unflatten keys in a JSON object
> unflatten: documentation for the unflatten function module

- source/rainerscript/functions/rs-get_property.rst
documentation for `get_property` built-in function in rsyslog PR #4471 https://github.com/rsyslog/rsyslog/pull/4471
> Documentation for built-in function `get_property`

- source/rainerscript/functions/rs-re_extract.rst
- source/rainerscript/functions/rs-re_extract_i.rst
- source/rainerscript/functions/rs-re_match_i.rst
see also https://github.com/rsyslog/rsyslog/pull/4574
> document new case-insensitive regex functions

- source/configuration/modules/imtcp.rst
see also https://github.com/rsyslog/rsyslog/pull/4585
> document new imtcp parameters

- source/configuration/modules/imtcp.rst
see also https://github.com/rsyslog/rsyslog/pull/4589
> document new imtcp input() parameters

- source/rainerscript/global.rst
see also https://github.com/rsyslog/rsyslog/pull/4575
> document new global option "parser.supportCompressionExtension"

- source/configuration/modules/imtcp.rst
see also https://github.com/rsyslog/rsyslog/pull/4623
> document new parameters

- source/configuration/modules/imfile.rst
imfile input option `ignoreOlderThan`
PR ref: https://github.com/rsyslog/rsyslog/pull/4626/
> imfile - add `ignoreOlderThan` input setting

- source/configuration/index.rst
- source/configuration/percentile_stats.rst
- source/rainerscript/functions/rs-percentile_observe.rst
reference: https://github.com/rsyslog/rsyslog/pull/4612
> Doc on percentile_stats module, and percentile_observe function

- source/tutorials/high_database_rate.rst
> fixing up merge issues (maybe)

- source/configuration/droppriv.rst
- source/rainerscript/global.rst
see also https://github.com/rsyslog/rsyslog/pull/4663
> document the privdrop. global() parameters

- source/configuration/modules/imhttp.rst
docs updated for https://github.com/rsyslog/rsyslog/pull/4470
> add description for basic auth option in imhttp

- source/configuration/modules/imrelp.rst
Some tidy up and rewording for the imrelp module.
> minor updates to imrelp documentation

- source/configuration/modules/ompgsql.rst
Corresponds to the changes added in PR https://github.com/rsyslog/rsyslog/pull/4762.
> ompgsql: update to reflect new conninfo feature

- source/configuration/actions.rst
Signed-off-by: Sergio Arroutbi <sarroutb@redhat.com>
> Document new action parameter "action.errorfile.maxsize"

- .gitignore
- source/configuration/modules/omelasticsearch.rst
Documentation update for https://github.com/rsyslog/rsyslog/pull/4592
> Add documentation of new JSON format

- source/configuration/modules/omelasticsearch.rst
see also https://github.com/rsyslog/rsyslog/pull/4808
> omelasticsearch: new config parameter

- source/configuration/modules/omelasticsearch.rst
Documentation for https://github.com/rsyslog/rsyslog/pull/4566
> omelasticsearch: document removal of mapping types

- source/configuration/modules/omfile.rst
This is to cover zstd enhanced functionality.
see also: https://github.com/rsyslog/rsyslog/pull/4903
> omfile: add doc for new module parameters

- source/configuration/modules/sigprov_ksi12.rst
General update to documentation. Not related to any specific task.
> sigprov_ksi12 doc updated after a long time.

- source/configuration/modules/sigprov_ksi12.rst
Relates to:
https://github.com/rsyslog/rsyslog/pull/4942
> New option sig.confInterval introduced.

- source/configuration/modules/sigprov_ksi12.rst
Relates to:
https://github.com/rsyslog/rsyslog/pull/4952
> New option sig.block.signTimeout introduced.

- source/configuration/modules/omhttp.rst
Nelson has been contributing to omhttp for over 3 years now along with Gabriel. He is currently main maintainer on it and updating this to reflect that.
FYI @gintrator @n2yen 
@rgerhards Let me know if any questions!
> Update maintainer info

- source/configuration/global/index.rst
- source/rainerscript/global.rst
Related change in rsyslog:
https://github.com/rsyslog/rsyslog/pull/4889
Signed-off-by: Sergio Arroutbi <sarroutb@redhat.com>
> Configure multiple additional extra CA files

- source/configuration/modules/imtcp.rst
see also: https://github.com/rsyslog/rsyslog/pull/4969
> document new parameter

- source/rainerscript/global.rst
also some small typo fixes
see also: https://github.com/rsyslog/rsyslog/pull/4904
> document new global parameter "abortOnFailedQueueStartup"

- source/troubleshooting/troubleshoot.rst
see also https://github.com/rsyslog/rsyslog/issues/4984
> clarify that -N command line option does need full config

- source/concepts/multi_ruleset.rst
> IP address misses its dot in the multi_ruleset.rst

- source/concepts/ns_gtls.rst
- source/concepts/ns_ossl.rst
- source/configuration/modules/sigprov_ksi12.rst
Documentation for Sha256 fingerprint authentication MR:  #4930
> add documentation for https://github.com/rsyslog/rsyslog/pull/4930

- source/configuration/modules/mmfields.rst
Thanks to Björn Pettersson for letting us know about the problem.
> fix typo which results in config errors

- source/configuration/modules/omfile.rst
see also: https://github.com/rsyslog/rsyslog/pull/5063
> document new omfile parameters

- source/rainerscript/functions/rs-substring.rst
Length of substring can now also be negative as a shortcut for some common situations.
see also: https://github.com/rsyslog/rsyslog/pull/5065
> improve doc of substring() function including new feature

- source/configuration/templates.rst
position.to can now be negative
see also https://github.com/rsyslog/rsyslog/pull/5070/files
> document new template property() option

- source/rainerscript/global.rst
Documents  https://github.com/rsyslog/rsyslog/pull/5144 .
> Document libcapng.default global option

- source/configuration/modules/imjournal.rst
Related PR: https://github.com/rsyslog/rsyslog/pull/5109
> imjournal: document FileCreateMode module parameter

- source/configuration/modules/imhiredis.rst
- source/configuration/modules/omhiredis.rst
linked to [rsyslog's PR #16](https://github.com/VultureProject/rsyslog/pull/16)
- [IMHIREDIS] description, new parameters and examples on the new 'stream' mode
- [OMHIREDIS] description, new parameters and examples on the new 'stream' mode
> New Redis streams functionality

- source/configuration/modules/imhiredis.rst
- source/rainerscript/global.rst
Document https://github.com/rsyslog/rsyslog/pull/5234
> Document libcapng.enable global option

- source/configuration/modules/imjournal.rst
Input modeule support change in
https://github.com/rsyslog/rsyslog/pull/5146
Added the new parameter and example usage.
> Documentation for imjournal input module support

- source/configuration/modules/imkmsg.rst
see also https://github.com/rsyslog/rsyslog/pull/5264
> imkmsg: document new module parameter

- source/configuration/modules/imkmsg.rst
see also https://github.com/rsyslog/rsyslog/pull/5278
> document new imkmsg module parameters

- source/configuration/modules/imjournal.rst
see https://github.com/rsyslog/rsyslog/pull/5286
> document new imjournal "defaultTag" module parameter

- source/configuration/modules/omhttp.rst
Update documentation to reflect new parameters and statistics counters being proposed for https://github.com/rsyslog/rsyslog/pull/5302/files
> add documentation for new omhttp parameters and statistic counters

- source/configuration/modules/imdtls.rst
- source/configuration/modules/omdtls.rst
closes https://github.com/rsyslog/rsyslog-doc/issues/1027 see also: https://github.com/rsyslog/rsyslog/pull/5280
> Add intitial doc for imdtls and omdtls modules

- source/configuration/modules/omfwd.rst
see also: https://github.com/rsyslog/rsyslog/pull/5369
> omfwd: document new parameter

- source/configuration/modules/omfwd.rst
see also: https://github.com/rsyslog/rsyslog/pull/5369
> omfwd: add new tcp target pool config parameters

- source/configuration/modules/imtcp.rst
see also: https://github.com/rsyslog/rsyslog/pull/5538
> document new imtcp parameter "socketBacklog"

- source/configuration/modules/omfwd.rst
closes https://github.com/rsyslog/rsyslog/issues/5552
> bugfix: omfwd can not "normally" be loaded in rsyslog.conf

- source/configuration/modules/imtcp.rst
see also https://github.com/rsyslog/rsyslog/pull/5497
closes https://github.com/rsyslog/rsyslog/issues/5579
> imtcp: update doc to new functionality and parameters
